#!/usr/bin/env ruby

require 'highline/import'

menu_prompt= <<EOS
1. Add song recommendation
2. List song recommendations
3. Exit
EOS

def print_help_info
  puts "[Help] Run as: ./mood_music manage"
end


if ARGV.length == 1
  if ARGV[0] == 'manage'
    choose do |menu|
      menu.choice('Add song recommendation') {say("")}
      menu.choice('List song recommendations') {say("No recommendations found.")}
      menu.choice('Exit') {say ("Peace Out!")}
    end
  elsif ARGV[0] == 'recommend'
    puts "What is your mood today?"
     choose do |menu|
       menu.choice('happy') {say("so youre happy")}
       menu.choice('sad') {say("so youre sad")}
       menu.choice('mellow') {say ("so youre mellow")}
       menu.choice('angry') {say ("so youre angry")}
      end
   else
     print_help_info
   end
else
  print_help_info
end
