#!/usr/bin/env ruby

require 'highline/import'
Dir["./app/**/*.rb"].each {|f| require f}
Dir["./lib/**/*.rb"].each {|f| require f}




def print_error_message
  puts "[Help] Run as: ./mood_music manage"
end

def list_recommendations
  say("No recommendations found.\n")
end

if ARGV[0].size == 1 and ARGV[0] == 'manage'
  choose do |menu|
    recommendations_controller = RecommendationsController.new
    menu.choice('Add song recommendation') {say("")}
    menu.choice('List song recommendations') {recommendations_controller.index}
    menu.choice('Exit') {say ("Peace Out!")}
   end
elsif ARGV[0].size == 1 and ARGV[0] == 'recommend'
  puts "What is your mood today?"
  choose do |menu|
    menu.choice('happy') {say("so youre happy")}
    menu.choice('sad') {say("so youre sad")}
    menu.choice('mellow') {say ("so youre mellow")}
    menu.choice('angry') {say ("so youre angry")}
  end
else
  print_error_message
end
